---
title: "\"GoTo <labelname>\" ist ungültig, da \"<labelname>\" sich innerhalb einer Try-, Catch- oder Finally-Anweisung befindet, die diese Anweisung nicht enthält"
ms.date: 07/20/2015
f1_keywords:
- bc30754
- vbc30754
helpviewer_keywords:
- BC30754
ms.assetid: 2eefc7fb-fdf0-41e9-bf60-c3bc93580e14
ms.openlocfilehash: 54fbd1852d60605290bef7816b05f7b9ffc8c673
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 06/04/2020
ms.locfileid: "84412545"
---
# <a name="goto-labelname-is-not-valid-because-labelname-is-inside-a-try-catch-or-finally-statement-that-does-not-contain-this-statement"></a>"GoTo \<labelname>" ist ungültig, da "\<labelname>" sich innerhalb einer Try-, Catch- oder Finally-Anweisung befindet, die diese Anweisung nicht enthält
Sie können nicht in einen `Try...Catch...Finally` -Block verzweigen.  
  
 **Fehler-ID:** BC30754  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
- Strukturieren Sie Ihren Code so um, dass die Beschriftung dem `Try...Catch...Finally` -Block vorangeht.  
  
## <a name="see-also"></a>Weitere Informationen

- [Try...Catch...Finally-Anweisung](../language-reference/statements/try-catch-finally-statement.md)
